# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 19:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Need',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('enable_beds', models.IntegerField()),
            ],
            options={
                'ordering': ['update'],
            },
        ),
        migrations.CreateModel(
            name='Refuge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=140)),
                ('coordinate_x', models.DecimalField(decimal_places=12, max_digits=24)),
                ('coordinate_y', models.DecimalField(decimal_places=12, max_digits=24)),
                ('city', models.CharField(max_length=40)),
                ('state', models.CharField(max_length=25)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refuge', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='refuge',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refuge', to='inventories.Refuge'),
        ),
        migrations.AddField(
            model_name='need',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventories.Post'),
        ),
    ]
